plugins {
    id 'java'
}

group = 'com.spectrasonic'
version = "${version}"

repositories {
    mavenCentral()
    
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }

    maven {
    name = "papermc"
    url = uri("https://repo.papermc.io/repository/maven-public/")
  }

}

dependencies {
    compileOnly("io.papermc.paper:paper-api:${paperVersion}-R0.1-SNAPSHOT")
}

jar {
    destinationDirectory = file("${rootDir}/out")
	archiveFileName = "${rootProject.name}.jar"
}

def targetJavaVersion = "${javaVersion}"

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}
